sudo: required
language: node_js
node_js:
  - "node"

git:
  depth: 2

services:
  - docker

cache:
  directories:
  - "$HOME/.npm"

env:
  global:
    - IMAGE_REPO=gcr.io/dd-decaf-cfbf6/memote-service-frontend

before_install:
  - npm install -g @vue/cli @vue/cli-service-global

install:
  - npm ci
  - npm run build

script:
  - npx vue-cli-service lint --no-fix
  - npm run test:unit

before_deploy:
  - ./scripts/install_gcloud.sh
  - ./scripts/install_kubectl.sh
  - docker build -t ${IMAGE_REPO}:${TRAVIS_COMMIT::12} -t ${IMAGE_REPO}:${TRAVIS_BRANCH} .
  - docker push ${IMAGE_REPO}:${TRAVIS_COMMIT::12}
  - docker push ${IMAGE_REPO}:${TRAVIS_BRANCH}

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    all_branches: true

notifications:
  email: false
  slack:
    rooms:
      secure: "bRxXW9fU315WevVSJK3xqFFSYCAM8ta3NHZlVWiOnbJJ/AmdLHFwthBSBJDY9Wgg2pgd243HRuyUCok7Pku3qyIr5RGpe7qPJ3y1/AWFv+uzBQ7FBHub2eaksy9DoLWYBLKS8+uHfj/xfNmuj+8BKKMH6Lcpz3/MiyzNAndPNjkW3ACmSWMn/yqzwoTZhEnkAUaj3qUP12eijbsJZ8qhBbWOoY/GgRRogl+zJgns2GBDUO6xhksKI2uFW8U1y/Uo1CxIntVVsowKmqhOeHO9tCZhr+zusLo+1iQsVnmv6w7C/Viho8Qrjp+rkmnhopjeWnUb8KrS5Ggg5j8lFvUR35yut9a8yhXxzpUpaRz9Ub9wfFQk5Zrzj9hQh+959MqYRnv+yltdUOl/Np5bmGgv4z9N7jeEpiEB4vzkJ/Yot4pdiYXelHeZszBobZYxdaXy3+48jgGMh/GBW+nmnBtSgKKvh6/wuSLBAiJsG0OMj9I2pb/2r68W7r+txMHmSgWs50zQxI1HOsXx6brq5gVTrQ8pLsXvn4Htw1wUjBqjtCM6DY/vWX5S6VYwK/PHegrZXbEDMxBDsKZJ8lz/pNjIQA1zqUixriV9S2Jj5mfyrZL+TFKnPHt0kAaxWi/0vmIQnWc4lcqbylmGmXYTIkf8JQpz3D6ngKNG+yL2EpoHTNE="
    on_success: change
    on_failure: change
    on_pull_requests: false
